### ISSUE TITLE
How can I incorporate this in a c++ or python application?

### ISSUE THREAD

**Issue by JeyP4** [DasEtwas/enginesound#1]
Hi

I like this development very much.

Could you please help me, how can I incorporate this with a c++ or python application.
Where I can on-the-fly play with volume and other parameters, when the audio play is live.
By the way, having a GUI may not be mandatory in this case.

Thanks

**Comment by DevNulPavel** [comment]
@JeyP4 You can build static or dynamic library with C-headers generated using bindgen, then use it in your code

**Comment by DevNulPavel** [comment]
@JeyP4 You can pass argument as classic C function parameters. Bindgen utility generates C headers which look like common C functions, then you need to link generated static Rust-lib to your C++ app.

See `crate-type = ["staticlib"]` for building static C-compatible library in Rust.

My small example with intagration Rust code with C++:
https://github.com/DevNulPavel/Rust_Examples/tree/master/rust_extention_lib

**Comment by DasEtwas** [comment]
Seems like @DevNulPavel answered this really well, closing
