### ISSUE TITLE
Diesel engine sound

### ISSUE THREAD

**Issue by e-malagon** [DasEtwas/enginesound#10]
Is it possible to use your library to simulate a diesel engine sound? Please can you provide me some advise?
Thanks in advance.

**Comment by DasEtwas** [comment]
I haven't used the tool in a while, but what I notice about diesel engines is that they tend to have much intake noise, a sharp ignition (small ignition time value) and a certain "breathiness", which can be set up by abusing the intake valve values, going into negative values even (unrealistic).

**Comment by flxtcat** [comment]
It'll be great if it is possible to integrate this engine sound to something like this rc sound engine https://github.com/TheDIYGuy999/Rc_Engine_Sound_ESP32. I was trying to do it but I don't have enough sound processing knowledge. Can you do something like this?.

**Comment by emalagonca** [comment]
I have the same idea, but to have the same behavior it is necessary to have the crank sound, the engine brake sound, and others. The idea looks great but there is still a lot of work to do.

**Comment by emalagonca** [comment]
@DasEtwas I tested the algorithm of this project on an stm32h7 MCU, unfortunately, it doesn't have the horsepower to achieve 44100 samples per second. An optimized version can achieve 11000 samples per second using something like 60% of the processor time but it doesn't sound so good. Also, I need the processing time to do other things. The MCU is one of the most advanced, so there is not too much room in the MCU market to look for alternatives, I will continue working on an alternative approach with fewer processing requirements. I appreciate the feedback that you gave me. Thanks.
