### ISSUE TITLE
Cargo build on Fedora fails

### ISSUE THREAD

**Issue by matchild** [DasEtwas/enginesound#4]
Hi! When running the "cargo build" command on linux (Fedora 33 64-bit) the compiler returns the following errors:
![image](https://user-images.githubusercontent.com/60429430/107990973-e4117a80-6fd5-11eb-92a8-4ed97bcbc8ff.png)

**Comment by matchild** [comment]
I managed to fix the first one by changing line 22 in main.rs:
use winit::platform::windows::WindowBuilderExtWindows; --> use winit::platform::unix::WindowBuilderExtUnix;

Do you have any hint as to what might be causing the second error?

**Comment by DasEtwas** [comment]
Fixed :) Thanks for reaching out

**Comment by matchild** [comment]
Thanks a lot!
