### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by matchild** [DasEtwas/enginesound#5]
Hi,
It would be awesome to change the rpms in real-time through stdin (and not only the slider in the GUI). This would help a lot in interfacing the simulator with other scripts!

**Comment by DasEtwas** [comment]
I'm hesitant to add this feature, as the crate exposes the generator struct as a library already. A C FFI would make more sense, as it can be accessed easily using python.

**Comment by matchild** [comment]
I know but since I am not very familiar with Rust I needed a quick/straightforward workaround..

I eventually managed to do it. For anyone wondering it was enough to add this to main.rs:
```
let mut generator = generator.clone();
	    loop {
	    	let n = get_input().trim().parse::<i64>().unwrap();
		let flt = n as f32;
		//println!("{}", flt);
		
		//generator.engine.rpm = flt;
		//engine.rpm=1000.0;
		
		//engine.rpm = flt;
		
		generator.write().engine.rpm=flt	
	    }

```


Where get_input() is defined as:
```
fn get_input() -> String {
    let mut buffer = String::new();
    std::io::stdin().read_line(&mut buffer).expect("Failed");
    buffer
}
```
(Thank you again for this awesome library)
