### ISSUE TITLE
Cargo run/build on Windows 10 fail

### ISSUE THREAD

**Issue by Saitodepaula** [DasEtwas/enginesound#6]
Hi, I'm totally new to Rust (the first contact I'm having with the language is to try to use this sofware), and I'm no professional in anything related to programming, so maybe I'm doing some obvious mistake here.

On Windows 10 64 bit, I've downloaded Rust, installed, downloaded Build Tools for Visual Studio 2019, and, using rustup, I've updated Rust to the nightly build.

When I type Cargo Run or Cargo Build in the directory I've unziped the 1.5.1 files, I've got the folowing:

```
error[E0658]: attributes on expressions are experimental
   --> src\main.rs:206:17
    |
206 |                 #[cfg(target_os = "windows")]
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #15701 <https://github.com/rust-lang/rust/issues/15701> for more information
    = help: add `#![feature(stmt_expr_attributes)]` to the crate attributes to enable

error: removing an expression is not supported in this position
   --> src\main.rs:206:17
    |
206 |                 #[cfg(target_os = "windows")]
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `enginesound`

To learn more, run the command again with --verbose.
```

There are 9 warnings before this, but are all related to never used functions or constants.

**Comment by DasEtwas** [comment]
Really just a lazy oversight of mine. Sorry! Thanks for reaching out :)

**Comment by Saitodepaula** [comment]
Thanks! I've been able to build it and run, but now I can't get a GUI. I've opened another issue.
