### ISSUE TITLE
No GUI when running on Windows 10

### ISSUE THREAD

**Issue by Saitodepaula** [DasEtwas/enginesound#7]
I've build and run the software, but there is no GUI, no audio file is generated, and I've got the message below.

```
C:\Users\marco\Desktop\enginesound-1.5.2\target\debug>enginesound
Headless builds do not supply GUI
Audio driver: Wasapi
Samplerate: 48000 Hz
Audio output device: Headphones (Logitech X300 Stereo)
Audio output format: StreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Default }
thread '<unnamed>' panicked at 'Failed to build audio output stream: StreamConfigNotSupported', src\audio.rs:73:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src\audio.rs:102:6
```

**Comment by DasEtwas** [comment]
Hmm, seems like windows doesnt provide the needed samplerate of 48000hz in this case. I thought this was a pretty standard samplerate, but this particular error can be seen as technical debt I left in from prototyping. Basically, one would need to resample the audio to the device's samplerate or generate at a fitting one using `--sample-rate` and whatever rate you can find in the audio settings for the device.

**Comment by DasEtwas** [comment]
Also, this would happen for mono output devices.

**Comment by Saitodepaula** [comment]
And about the GUI? Is there something I can do to be able to use the GUI?

**Comment by DasEtwas** [comment]
Adjusting the samplerate would probably suffice to get everything working. Other than that, I don't see a use of the GUI if you can't listen to the sound..

**Comment by Saitodepaula** [comment]
Maybe I'm getting wrong how this software works, do I need a sound file _before_ I run the software?

**Comment by DasEtwas** [comment]
`enginesound.exe --sample-rate <your samplerate found in windows settings>`

**Comment by Saitodepaula** [comment]
My sample rate is 44.100, working now, thanks!

**Comment by DasEtwas** [comment]
Excellent!
