### ISSUE TITLE
Dependencies to alsa, libxcb-shape0-dev and libxcb-xfixes0-dev

### ISSUE THREAD

**Issue by leosh64** [DasEtwas/enginesound#9]
Hey,

thanks for providing the code for this great project!

When trying to build your project on a vanilla Ubuntu (focal) system, I had to install several additional packages to get through the build process:

## Errors

```
error: failed to run custom build command for `alsa-sys v0.3.0`
```

```
  = note: /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
```

## Solution

Install packages `libasound2-dev`, `libxcb-shape0-dev` and `libxcb-xfixes0-dev`, e.g. via:
```
sudo apt-get install libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev
```

Maybe these dependencies could be added to the README.md file to make it transparent what's required.

**Comment by DasEtwas** [comment]
Thanks :) 👍
